import { useAuth } from '@/features/auth/AuthProvider'
import useLogsManagement from './useLogsManagement'
import useTestManagement from './useTestManagement'
import useDashboardUI from './useDashboardUI'

export default function useDashboard() {
  const { user } = useAuth()

  // Use specialized hooks for different concerns
  const logsManagement = useLogsManagement(user)
  const testManagement = useTestManagement(user)
  const ui = useDashboardUI()

  // Combine all the functionality
  return {
    // Logs Management
    ...logsManagement,
    
    // Test Management
    ...testManagement,
    
    // UI State
    ...ui,
    
    // Convenience functions that combine multiple concerns
    handleAddLog: async (e) => {
      e.preventDefault()
      
      // Extract form values from the current newLog state
      const { user_query, model_response } = ui.newLog
      // Auto-generate model response if empty
      const response = (model_response && model_response.trim().length > 0)
        ? model_response
        : await (async () => {
            try {
              // For now, we'll just return a placeholder - in a real app you might call an AI service
              return "This is a placeholder response. In a real application, this would be generated by an AI model.";
            } catch (error) {
              console.error('Ask model error:', error)
              return "Error generating response. Please try again."
            }
          })()
      
      // Create log entry
      const entry = {
        user_query: user_query.trim(),
        model_response: response.trim(),
        validation_score: 0, // Will be updated by the validation service
        external_verification_required: false,
        notes: '',
        validators: [],
        status: 'pending',
        created_by: user?.email || 'unknown',
        timestamp: new Date().toISOString(),
        source: 'manual'
      }
      
      try {
        await logsManagement.addLog(entry)
        ui.resetNewLog()
        ui.toggleAddForm()
      } catch (error) {
        console.error('Add log error:', error)
      }
    }
  }
}